site_name: Nazuna
theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.expand
extra_css:
  - custom.css
nav:
  - Home: index.md
  - How to Run: how_to_run.md
  - Reference:
    - Task Runners: reference_task_runners.md
    - Models: reference_models.md
    - Others: reference_others.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CookieBox26/nazuna
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            heading_level: 3
            show_root_heading: true
            docstring_section_style: list
            show_source: false
            show_bases: true
            filters: []
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
