[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "nazuna"
version = "0.0.1"
description = "Utility functions for time-series data analysis"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "CookieBox26", email = "cookie-box@cookie-box.info" },
]
dependencies = [
    "toml==0.10.2",
    "numpy==2.4.1",
    "pandas==2.3.3",
    "matplotlib==3.10.8",
    "statsmodels==0.14.6",
    "optuna==4.7.0",
    "jinja2==3.1.6",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
torch-cpu = [
    "torch==2.10.0",
]
torch-cu130 = [
    "torch==2.10.0+cu130",
]
torch-cu126 = [
    "torch==2.9.1+cu126",
]
dev = [
    "pre-commit",
    "pytest",
    "ruff",
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings-python",
]

[project.scripts]
nazuna = 'nazuna.__main__:main'

[project.urls]
GitHub = "https://github.com/CookieBox26/nazuna"
Documentation = "https://nazuna.readthedocs.io/en/latest/"

[tool.hatch.build.targets.wheel]
artifacts = [ "nazuna/datasets/**/*.csv",]

[tool.pytest.ini_options]
addopts = "-q -m 'not slow'"
markers = [ "slow: time-consuming tests",]
filterwarnings = [
  "ignore:.*The NVIDIA driver on your system is too old.*:UserWarning",
]

[tool.ruff.lint]
select = [ "F401", "F821", "F841", "E722",]

[tool.uv]
conflicts = [
    [
        { extra = "torch-cpu" },
        { extra = "torch-cu130" },
        { extra = "torch-cu126" },
    ],
]
sources = { "torch" = [
    { extra = "torch-cpu", index = "idx_torch-cpu" },
    { extra = "torch-cu130", index = "idx_torch-cu130" },
    { extra = "torch-cu126", index = "idx_torch-cu126" },
] }
[[tool.uv.index]]
name = "idx_torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
[[tool.uv.index]]
name = "idx_torch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
[[tool.uv.index]]
name = "idx_torch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
