out_dir = "./out/jma11_baselines"
exist_ok = true

# =============== data ===============
data = "JMA11"

# =============== definitions ===============
definition_includes = [
{ bundled = "common" },
{ bundled = "datasets" },
]

[definition_includes_data]
n_channel = 11
seq_len_sample = 193
pred_len_sample = 24
seq_len_raw = 97
pred_len = 24
period_len = 24

# =============== tasks ===============
[[tasks]]
task_type = "eval"
name = "Eval LastValue"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "LastValue"

[[tasks]]
task_type = "eval"
name = "Eval Last1Cycle"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "Last1Cycle"

[[tasks]]
task_type = "eval"
name = "Eval Last2Cycles"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "Last2Cycles"

[[tasks]]
task_type = "eval"
name = "Eval Last4Cycles"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "Last4Cycles"

[[tasks]]
task_type = "eval"
name = "Eval Last1CycleD"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "Last1CycleD"

[[tasks]]
task_type = "eval"
name = "Eval Last2CyclesD"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "Last2CyclesD"

[[tasks]]
task_type = "eval"
name = "Eval Last4CyclesD"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "Last4CyclesD"
