out_dir = "./out/jma_train_dlinear"
exist_ok = true

# =============== data ===============
[data]
path = [ "jma", "weather_japan_hourly_2025-09-01_2025-12-31_27_blocks.csv",]
colname_timestamp = "timestamp"
seq_len = 97  # 24 * 4 + 1
pred_len = 24
white_list = "temp_fukuoka,temp_osaka,temp_tokyo,temp_sendai"

# =============== definitions ===============
[definitions]
DataRangeEval = [ 0.8, 1.0,]
DataRangeTrain = [ 0.0, 0.8,]
DataRangeEvalPilot = [ 0.6, 0.8,]
DataRangeTrainPilot = [ 0.0, 0.6,]

[definitions.MAE]
cls_path = "nazuna.criteria.MAE"
params = { n_channel = 4, pred_len = 24 }

[definitions.ImprovementRate]
cls_path = "nazuna.criteria.ImprovementRate"
params = { n_channel = 4, pred_len = 24, error_type = "mae" }

[definitions.SimpleAverage]
cls_path = "nazuna.models.simple_average.SimpleAverage"
params = { seq_len = 96, pred_len = 24, period_len = 24, prep_type = "diff" }

[definitions.DLinear]
cls_path = "nazuna.models.dlinear.DLinear"
[definitions.DLinear.params]
seq_len = 97
pred_len = 24
kernel_size = 25
bias = true
scaler_cls_path = "nazuna.models.common.IqrScaler"
scaler_params = { stat_types = [ "qtile_full", "saved",] }
use_lc = true
lc_end_epoch = 20
lc_rate = 0.9

[definitions.BatchSamplerShuffle]
cls_path = "nazuna.batch_samplers.BatchSamplerShuffle"
params = { batch_size = 32 }

[definitions.Adam]
cls_path = "torch.optim.Adam"
params = { lr = 0.0001 }

[definitions.CosineAnnealingLR]
cls_path = "torch.optim.lr_scheduler.CosineAnnealingLR"
params = { T_max = 100 }

# =============== tasks ===============
[[tasks]]
task_type = "eval"
name = "Eval Baseline"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "SimpleAverage"

[[tasks]]
task_type = "train"
name = "Pilot"
data_range_train = "DataRangeTrainPilot"
data_range_eval = "DataRangeEvalPilot"
criterion = "MAE"
model = "DLinear"
batch_sampler = "BatchSamplerShuffle"
optimizer = "Adam"
lr_scheduler = "CosineAnnealingLR"
n_epoch = 5
early_stop = true

[[tasks]]
task_type = "train"
name = "Train"
data_range_train = "DataRangeTrain"
criterion = "MAE"
model = "DLinear"
batch_sampler = "BatchSamplerShuffle"
optimizer = "Adam"
lr_scheduler = "CosineAnnealingLR"
n_epoch = { task_name = "Pilot" }

[[tasks]]
task_type = "eval"
name = "Eval"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "DLinear"
model_state = { task_name = "Train" }

[[tasks]]
task_type = "eval"
name = "Eval ImpRate"
data_range_eval = "DataRangeEval"
criterion = "ImprovementRate"
baseline_model = "SimpleAverage"
model = "DLinear"
model_state = { task_name = "Train" }
