out_dir = "./out/jma_train_dlinear"
exist_ok = true

# =============== data ===============
data = "JMA4"

# =============== definitions ===============
definition_includes = [
{ bundled = "common" },
{ bundled = "dlinear" },
]

[definition_includes_data]
n_channel = 4
seq_len = 97
pred_len = 24
period_len = 24

[definitions.JMA4]
colname_timestamp = "timestamp"
seq_len = 97  # 24 * 4 + 1
pred_len = 24
white_list = "temp_fukuoka,temp_osaka,temp_tokyo,temp_sendai"
[definitions.JMA4.path]
category = "jma"
filename = "weather_japan_hourly_2025-09-01_2025-12-31_27_blocks.csv"

# =============== tasks ===============
[[tasks]]
task_type = "eval"
name = "Eval Baseline"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "Last4CyclesD"
dump_pred_data = false

[[tasks]]
task_type = "train"
name = "Pilot 0"
data_range_train = "DataRangeTrainPilot"
data_range_eval = "DataRangeEvalPilot"
criterion = "MAE"
model = "DLinear"
batch_sampler = "BSS32"
optimizer = "Adam00001"
lr_scheduler = "CosineAnnealingLR100"
n_epoch = 5
early_stop = true

[[tasks]]
task_type = "train"
name = "Train 0"
data_range_train = "DataRangeTrain"
criterion = "MAE"
model = "DLinear"
batch_sampler = "BSS32"
optimizer = "Adam00001"
lr_scheduler = "CosineAnnealingLR100"
n_epoch = { task_name = "Pilot 0" }

[[tasks]]
task_type = "eval"
name = "Eval 0"
data_range_eval = "DataRangeEval"
criterion = "MAE"
model = "DLinear"
model_state = { task_name = "Train 0" }

[[tasks]]
task_type = "eval"
name = "Eval ImpRate 0"
data_range_eval = "DataRangeEval"
criterion = "ImprovementRate"
baseline_model = "Last4CyclesD"
model = "DLinear"
model_state = { task_name = "Train 0" }
