out_dir = "./out/traffic8_linears"
exist_ok = true

# =============== data ===============
data = "Traffic8"

# =============== definitions ===============
definition_includes = [
{ bundled = "common" },
{ bundled = "datasets" },
{ bundled = "dlinear" },
]

[definition_includes_data]
n_channel = 8
seq_len_sample = 1344
pred_len_sample = 168
seq_len_raw = 672
pred_len = 168
period_len = 168

[definitions]
Cyclic = { base = "Last4Cycles" }

[definitions.NLinearStacked0]
base = "NLinearStacked"
[definitions.NLinearStacked0.params]
use_cross = false
reg_pred_self = 0.0001
reg_coef_self = 0.1

[definitions.NLinearStacked1]
base = "NLinearStacked"
[definitions.NLinearStacked1.params]
use_cross = true
reg_pred_self = 0.0001
reg_coef_self = 0.1
reg_pred_cross = 0.1
reg_coef_cross = 0.1

# =============== template ===============
[template]
template_type = "train_with_baseline_multiparams"
criterion_eval = "MAE"
criterion_target = "MAE"
criterion_imprate = "ImprovementRate"
baseline_model = "Cyclic"
model = ""
data_range_eval = "DataRangeEval"
data_range_train = "DataRangeTrain"
data_range_eval_pilot = "DataRangeEvalPilot"
data_range_train_pilot = "DataRangeTrainPilot"
batch_sampler = "BSS16"
optimizer = "Adam0001"
lr_scheduler = "ExponentialLR09"
n_epoch = 0

[[template.params]]
nopilot = true
seed = 0
model = "NLinear"
criterion_target = "MAE"
batch_sampler = "BSS16"
optimizer = "Adam0001"
lr_scheduler = "ExponentialLR09"
n_epoch = 48

[[template.params]]
nopilot = true
seed = 0
model = "NLinear"
criterion_target = "MAE09"
batch_sampler = "BSS16"
optimizer = "Adam0001"
lr_scheduler = "ExponentialLR09"
n_epoch = 48

[[template.params]]
nopilot = true
seed = 0
model = "NLinearStacked0"
criterion_target = "MAE"
batch_sampler = "BSS16"
optimizer = "Adam0001"
lr_scheduler = "ExponentialLR09"
n_epoch = 48

[[template.params]]
nopilot = true
seed = 0
model = "NLinearStacked1"
criterion_target = "MAE"
batch_sampler = "BSS16"
optimizer = "Adam0001"
lr_scheduler = "ExponentialLR09"
n_epoch = 48
